/**
 * Machine-readable API error codes.
 * Documented in docs/errors.md and Swagger ErrorResponse schema.
 */
export const ErrorCode = {
  // Authentication
  INVALID_API_KEY: "INVALID_API_KEY",
  API_KEY_REVOKED: "API_KEY_REVOKED",
  API_KEY_EXPIRED: "API_KEY_EXPIRED",
  MERCHANT_INACTIVE: "MERCHANT_INACTIVE",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ACCOUNT_NOT_VERIFIED: "ACCOUNT_NOT_VERIFIED",
  ACCOUNT_NOT_ACTIVE: "ACCOUNT_NOT_ACTIVE",
  AUTHENTICATION_REQUIRED: "AUTHENTICATION_REQUIRED",
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_TOKEN: "INVALID_TOKEN",
  TOKEN_MISSING: "TOKEN_MISSING",
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
  ADMIN_TOKEN_REQUIRED: "ADMIN_TOKEN_REQUIRED",
  INVALID_ADMIN_TOKEN: "INVALID_ADMIN_TOKEN",
  ADMIN_AUTH_REQUIRED: "ADMIN_AUTH_REQUIRED",
  AUTHENTICATION_FAILED: "AUTHENTICATION_FAILED",
  AUTHENTICATION_ERROR: "AUTHENTICATION_ERROR",
  INVALID_AUTH_CREDENTIALS: "INVALID_AUTH_CREDENTIALS",

  // Merchant
  MERCHANT_NOT_FOUND: "MERCHANT_NOT_FOUND",
  EMAIL_ALREADY_REGISTERED: "EMAIL_ALREADY_REGISTERED",
  INVALID_STATUS_VALUE: "INVALID_STATUS_VALUE",
  INVALID_MERCHANT_IDS: "INVALID_MERCHANT_IDS",
  REASON_REQUIRED: "REASON_REQUIRED",
  ACCOUNT_ALREADY_ANONYMIZED: "ACCOUNT_ALREADY_ANONYMIZED",
  DELETION_REQUEST_NOT_FOUND: "DELETION_REQUEST_NOT_FOUND",
  NO_DELETION_REQUEST: "NO_DELETION_REQUEST",

  // Payment
  PAYMENT_NOT_FOUND: "PAYMENT_NOT_FOUND",
  PAYMENT_EXPIRED: "PAYMENT_EXPIRED",
  PAYMENT_ALREADY_CONFIRMED: "PAYMENT_ALREADY_CONFIRMED",
  PAYMENT_CREATE_FAILED: "PAYMENT_CREATE_FAILED",
  PAYMENT_FETCH_FAILED: "PAYMENT_FETCH_FAILED",

  // Rate limit
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  PAYMENT_RATE_LIMIT: "PAYMENT_RATE_LIMIT",
  API_KEY_RATE_LIMIT: "API_KEY_RATE_LIMIT",
  EMERGENCY_RATE_LIMIT_EXCEEDED: "EMERGENCY_RATE_LIMIT_EXCEEDED",
  OTP_SMS_RATE_LIMIT: "OTP_SMS_RATE_LIMIT",
  CAPTCHA_REQUIRED: "CAPTCHA_REQUIRED",

  // Validation
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_REQUEST_BODY: "INVALID_REQUEST_BODY",
  MISSING_REQUIRED_FIELD: "MISSING_REQUIRED_FIELD",
  INVALID_METADATA: "INVALID_METADATA",
  METADATA_TOO_LARGE: "METADATA_TOO_LARGE",
  INVALID_AMOUNT: "INVALID_AMOUNT",
  INVALID_CURRENCY: "INVALID_CURRENCY",
  INVALID_EMAIL: "INVALID_EMAIL",
  INVALID_DATE_RANGE: "INVALID_DATE_RANGE",
  INVALID_ENVIRONMENT: "INVALID_ENVIRONMENT",
  INVALID_MERCHANT_ID: "INVALID_MERCHANT_ID",
  NO_FILE_UPLOADED: "NO_FILE_UPLOADED",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",

  // Settlement
  SETTLEMENT_NOT_FOUND: "SETTLEMENT_NOT_FOUND",
  SETTLEMENT_FAILED: "SETTLEMENT_FAILED",
  NO_BANK_ACCOUNT: "NO_BANK_ACCOUNT",
  INVALID_BANK_ACCOUNT: "INVALID_BANK_ACCOUNT",

  // API Key
  API_KEY_NOT_FOUND: "API_KEY_NOT_FOUND",
  API_KEY_ALREADY_REVOKED: "API_KEY_ALREADY_REVOKED",
  MAX_ACTIVE_KEYS: "MAX_ACTIVE_KEYS",
  API_KEY_CREATE_FAILED: "API_KEY_CREATE_FAILED",
  API_KEY_LIST_FAILED: "API_KEY_LIST_FAILED",
  API_KEY_REVOKE_FAILED: "API_KEY_REVOKE_FAILED",

  // Webhook
  INVALID_WEBHOOK_URL: "INVALID_WEBHOOK_URL",
  WEBHOOK_DELIVERY_FAILED: "WEBHOOK_DELIVERY_FAILED",
  WEBHOOK_LOG_NOT_FOUND: "WEBHOOK_LOG_NOT_FOUND",
  WEBHOOK_ALREADY_DELIVERED: "WEBHOOK_ALREADY_DELIVERED",
  WEBHOOK_SECRET_NOT_CONFIGURED: "WEBHOOK_SECRET_NOT_CONFIGURED",
  WEBHOOK_REQUEUE_FAILED: "WEBHOOK_REQUEUE_FAILED",
  LOG_ID_REQUIRED: "LOG_ID_REQUIRED",

  // KYC
  KYC_ALREADY_SUBMITTED: "KYC_ALREADY_SUBMITTED",
  KYC_NOT_FOUND: "KYC_NOT_FOUND",
  KYC_APPROVED: "KYC_APPROVED",
  KYC_REJECTED: "KYC_REJECTED",
  KYC_ALREADY_APPROVED: "KYC_ALREADY_APPROVED",

  // Refund
  REFUND_NOT_FOUND: "REFUND_NOT_FOUND",
  REFUND_ALREADY_PROCESSED: "REFUND_ALREADY_PROCESSED",
  INSUFFICIENT_FUNDS: "INSUFFICIENT_FUNDS",
  REFUND_PERIOD_EXPIRED: "REFUND_PERIOD_EXPIRED",
  REFUND_ID_REQUIRED: "REFUND_ID_REQUIRED",

  // Invoice
  INVOICE_NOT_FOUND: "INVOICE_NOT_FOUND",
  INVOICE_ALREADY_PAID: "INVOICE_ALREADY_PAID",
  INVOICE_VOIDED: "INVOICE_VOIDED",
  INVOICE_NOT_DRAFT: "INVOICE_NOT_DRAFT",
  INVOICE_ALREADY_VOIDED: "INVOICE_ALREADY_VOIDED",
  CANNOT_VOID_PAID_INVOICE: "CANNOT_VOID_PAID_INVOICE",
  PDF_GENERATION_FAILED: "PDF_GENERATION_FAILED",

  // Payment link
  PAYMENT_LINK_NOT_FOUND: "PAYMENT_LINK_NOT_FOUND",
  PAYMENT_LINK_INACTIVE: "PAYMENT_LINK_INACTIVE",
  PAYMENT_LINK_EXPIRED: "PAYMENT_LINK_EXPIRED",

  // Customer
  CUSTOMER_NOT_FOUND: "CUSTOMER_NOT_FOUND",
  CUSTOMER_ALREADY_EXISTS: "CUSTOMER_ALREADY_EXISTS",

  // Escrow
  ESCROW_ALREADY_INITIALIZED: "ESCROW_ALREADY_INITIALIZED",
  ESCROW_INIT_FAILED: "ESCROW_INIT_FAILED",
  PAYMENT_NOT_ESCROW: "PAYMENT_NOT_ESCROW",
  ESCROW_ALREADY_RELEASED: "ESCROW_ALREADY_RELEASED",
  ESCROW_RELEASE_FAILED: "ESCROW_RELEASE_FAILED",
  ESCROW_ALREADY_REFUNDED: "ESCROW_ALREADY_REFUNDED",
  CANNOT_REFUND_RELEASED_ESCROW: "CANNOT_REFUND_RELEASED_ESCROW",
  ESCROW_REFUND_FAILED: "ESCROW_REFUND_FAILED",
  UNKNOWN_EVENT_TYPE: "UNKNOWN_EVENT_TYPE",

  // Reconciliation / reports
  REPORT_NOT_FOUND: "REPORT_NOT_FOUND",
  ALERT_ID_REQUIRED: "ALERT_ID_REQUIRED",

  // Data export
  EXPORT_JOB_NOT_FOUND: "EXPORT_JOB_NOT_FOUND",
  EXPORT_NOT_READY: "EXPORT_NOT_READY",
  EXPORT_EXPIRED: "EXPORT_EXPIRED",
  EXPORT_PAYLOAD_MISSING: "EXPORT_PAYLOAD_MISSING",

  // Idempotency
  MISSING_IDEMPOTENCY_KEY: "MISSING_IDEMPOTENCY_KEY",
  INVALID_IDEMPOTENCY_KEY: "INVALID_IDEMPOTENCY_KEY",
  IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT",
  IDEMPOTENCY_CHECK_FAILED: "IDEMPOTENCY_CHECK_FAILED",

  // Notification preferences
  INVALID_REMINDER_MINUTES: "INVALID_REMINDER_MINUTES",

  PLAN_LIMIT_EXCEEDED: "PLAN_LIMIT_EXCEEDED",

  // Misc
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  FX_FETCH_FAILED: "FX_FETCH_FAILED",
  POOL_STATS_FAILED: "POOL_STATS_FAILED",
  CHECKOUT_SSE_UNAVAILABLE: "CHECKOUT_SSE_UNAVAILABLE",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  DATABASE_ERROR: "DATABASE_ERROR",
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];

/** All error codes for Swagger enum documentation */
export const ERROR_CODE_VALUES: ErrorCodeType[] = Object.values(ErrorCode);
